spring.datasource.url=jdbc:postgresql://localhost:5432/lab
spring.datasource.username=emt
spring.datasource.password=emt

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE